### PR TITLE
UIMARCAUTH-440: add missed `ui-data-export.edit` permission

### PR DESCRIPTION
**Pull request by aidynoJ**
## Purpose
[UIMARCAUTH-40](https://folio-org.atlassian.net/browse/UIMARCAUTH-440) - Export (MARC) option is missing in Actions menu

### CODE REVIEW

**Review by zburke — COMMENTED** [review]
I think this ticket was filed erroneously. [AuthorityView.js](https://github.com/folio-org/ui-marc-authorities/blob/65c17abb2aabb7ed58020b0d9bafb4343a452c8e/src/views/AuthorityView/AuthorityView.js#L119) specifically checks for the permission `ui-data-export.edit` implying the permission _should_ be controlled via ui-data-export rather than a locally-defined permission-set. 

I see two options:
1. Close the ticket as "Won't do"
2. Update `package.json` with a new permission set (maybe. `ui-marc-authorities.authority-record.export.execute`?) and change `AuthorityView.js` to refer to the local pset instead. 

Unrelated, this work doesn't seem to have anything to do with Eureka. How did this land on our plate?

**Comment by aidynoJ** [comment]
@zburke   So, probably it is not even a bug and we can close it as 'not a bug anymore'. It was intentionally made based on [UIMARCAUTH-422](https://folio-org.atlassian.net/browse/UIMARCAUTH-422) story. Sorry, I'm was not super familiar with relations of that modules.

**Comment by BogdanDenis** [comment]
@aidynoJ I agree with @zburke 1st point that we check if a user has Data Export permissions. Giving `ui-data-export.edit` to anyone who has access to MARC Authorities app doesn't make sense to me.
Let me discuss it with our POs, but I think we'll most likely close it as Won't do

**Comment by BogdanDenis** [comment]
Discussed the ticket with Spitfire's PO and decided that it's not a bug and can be closed

**Pull request closed without merging**
